@extends('layouts.main')
@section('content')
    <section class="inner_banner" style="background-image: url('{{ asset('assets/images/privacy/terms-banner.jpg') }}')">
        <div class="container">
            <div class="inner_banner_content">
                <h1>
                    Privacy Policy
                </h1>
                <ul class="pagination">
                    <li>
                        <a class="first" href="{{ Route('index') }}">Home</a>
                    </li>
                    <li>Privacy Policy</li>
                </ul>
            </div>
        </div>
    </section>


    <section class="main-sec">
        <div class="container">
            <p class="main-sec-top-para">
                Last updated 25/07/2024. The following privacy policy are relevant and applicable to all bookings
                made with <span class="main-sec-clr">IMAS MEDICAL.</span>
            </p>


            <ol class="main-sec-list wow fadeInUp" data-wow-duration="1s">
                <li class="list-name"><span class="list-head wow fadeInUp" data-wow-duration="1s">Introduction</span> 
                    <ol class="main-sec-list2 wow fadeInUp" data-wow-duration="1s">
                        <li>We are committed to safeguarding the privacy of our website visitors, service users, and individual customers.</li>
                        <li>This policy applies where we are acting as a data controller with respect to the personal data of such persons; in other words, where we determine the purposes and means of the processing of that personal data.</li>
                        <li>Our website incorporates privacy controls which affect how we will process your personal data. By using the privacy controls, you can specify whether you would like to receive direct marketing communications and limit the collection, sharing and publication of your personal data. You can access the privacy controls via [www.imasmedical.com].</li>
                        <li>This disclaimer shall govern your use of our website and the terms and conditions
                            attached to
                            using our driver medical service. </li>
                        <li> We use cookies on our website. Insofar as those cookies are not strictly necessary for the provision of our website and services, we will ask you to consent to our use of cookies when you first visit our website.</li>
                        <li>In this policy, “we”, “us” and “our”; refer to <span class="main-sec-clr">IMAS MEDICAL.</span></li>
                    </ol>

                </li>
                <li class="list-name wow fadeInUp" data-wow-duration="1s"><span class="list-head wow fadeInUp" data-wow-duration="1s">The data that we collect</span>
                    <ol class="main-sec-list wow fadeInUp" data-wow-duration="1s">
                        <li>In this Section 2 we have set out the general categories of personal data that we process and, in the case of personal data that we did not obtain directly from you, information about the source and specific categories of that data.</li>
                        <li> We may be collect, hold and store data such as contact details, medical history, occupational history, health surveillance data. The source of the contact data is you and/or your employer.</li>
                        <li> We may process data enabling us to get in touch with you (“contact data”). The contact data may include your name, email address, telephone number, postal address and/or social media account identifiers. The source of the contact data is you and/or your employer.</li>
                        <li>We may process your website user account data (“account data”). The account data may include your account identifier, name, email address, business name, account creation and modification dates, website settings and marketing preferences. The primary source of the account data is you and/or your employer, although some elements of the account data may be generated by our website.</li>
                        <li> We may process information relating to transactions, including purchases of goods and/or services, that you enter into with us and/or through our website (“transaction data”). The transaction data may include your name, your contact details, your payment card details (or other payment details) and the transaction details. The source of the transaction data is you and/or our payment services provider.</li>
                        <li> We may process information contained in or relating to any communication that you send to us or that we send to you (“communication data”). The communication data may include the communication content and metadata associated with the communication. Our website will generate the metadata associated with communications made using the website contact forms.</li>
                        <li> We may process data about your use of our website and services (“usage data”). The usage data may include your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views and website navigation paths, as well as information about the timing, frequency and pattern of your service use. The source of the usage data is our analytics tracking system.</li>
                    </ol>
                </li>
                <li class="list-name wow fadeInUp" data-wow-duration="1s"><span class="list-head wow fadeInUp" data-wow-duration="1s">Purposes of processing and legal bases</span>
                    <ol class="main-sec-list wow fadeInUp" data-wow-duration="1s">
                        <li> In this Section 3, we have set out the purposes for which we may process personal data and the legal bases of the processing.</li>
                        <li>We may process your personal data for the purposes of operating our website, the processing and fulfilment of orders, providing our services, supplying our goods, generating invoices, bills and other payment-related documentation, and credit control. </li>
                        <li>We may process account data for the purposes of publishing such data on our website and elsewhere through our services in accordance with your express instructions. The legal basis for this processing is the publication of content in the ordinary course of our operations.</li>
                        <li> We may process contact data, account data, transaction data and/or communication data for the purposes of managing our relationships, communicating with you by email, SMS, post, fax and/or telephone, providing support services and complaint handling. The legal basis for this processing is communications with our website visitors, service users, individual customers and customer personnel, the maintenance of relationships, and the proper administration of our website, services and business.</li>
                        <li> We may process contact data, account data and/or transaction data for the purposes of creating, targeting and sending direct marketing communications by email, SMS, post and/or fax and making contact by telephone for marketing-related purposes. The legal basis for this processing is promoting our business and communicating marketing messages and offers to our website visitors and service users.</li>
                        <li>We may process usage data and/or transaction data for the purposes of researching and analysing the use of our website and services, as well as researching and analysing other interactions with our business. The legal basis for this processing is for monitoring, supporting, improving and securing our website, services and business generally.</li>
                        <li>We may process your personal data for the purposes of creating and maintaining our databases, back-up copies of our databases and our business records generally. The legal basis for this processing is to ensure that we have access to all the information we need to properly and efficiently run our business in accordance with this policy.</li>
                        <li> We may process your personal data for the purposes of security and the prevention of fraud and other criminal activity. The legal basis of this processing is for the protection of our website, services and business, and the protection of others.</li>
                        <li>We may process your personal data where necessary for the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure. The legal basis for this processing is for the protection and assertion of our legal rights, your legal rights and the legal rights of others.</li>

                    </ol>
                </li>
                <li class="list-name wow fadeInUp" data-wow-duration="1s"><span class="list-head wow fadeInUp" data-wow-duration="1s">Providing your personal data to others</span>
                    <ol class="main-sec-list wow fadeInUp" data-wow-duration="1s">
                        <li>Your personal data held in our website database will be stored on the servers of our hosting services providers.</li>
                        <li> In addition to the specific disclosures of personal data set out in this Section 4, we may disclose your personal data where such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.</li>
                    </ol>

                </li>
                <li class="list-name wow fadeInUp" data-wow-duration="1s"><span class="list-head  wow fadeInUp" data-wow-duration="1s">Data retention</span>
                    <ol class="main-sec-list wow fadeInUp" data-wow-duration="1s">
                        <li>This Section 5 sets out our data retention policies and procedures, which are designed to help ensure that we comply with our legal obligations in relation to the retention and deletion of personal data.</li>
                        <li>Personal data that we process for any purpose or purposes shall not be kept for longer than is necessary for that purpose or those purposes.</li>
                        <li>We will retain your personal data for a maximum period of 2 years.</li>
                        <li>Notwithstanding the other provisions of this Section 5, we may retain your personal data where such retention is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.</li>
                    </ol>
                </li>
                <li class="list-name wow fadeInUp" data-wow-duration="1s"><span class="list-head wow fadeInUp" data-wow-duration="1s">Your rights</span>
                    <ol class="main-sec-list wow fadeInUp" data-wow-duration="1s">
                        <li> In this Section 6, we have listed the rights that you have under data protection law.</li>
                        <li>Your principal rights under data protection law are:
                            <ol class="list-style-a">
                                <li>the right to access – you can ask for copies of your personal data;</li>
                                <li>the right to rectification – you can ask us to rectify inaccurate personal data and to complete incomplete personal data;</li>
                                <li>the right to restrict processing – you can ask us to restrict the processing of your personal data;</li>
                                <li>the right to object to processing – you can object to the processing of your personal data;</li>
                                <li>the right to data portability – you can ask that we transfer your personal data to another organisation or to you;</li>
                                <li>the right to complain to a supervisory authority – you can complain about our processing of your personal data; and</li>
                                <li> the right to withdraw consent – to the extent that the legal basis of our processing of your personal data is consent, you can withdraw that consent.</li>
                            </ol>
                        </li>
                        <li>You may exercise any of your rights in relation to your personal data by written notice to us.</li>                       
                    </ol>
            </ol>
        </div>
    </section>

@endsection
